### PR TITLE
Try fixing CI issue

### PR DESCRIPTION
**Pull request by Eskibear**
image

### CODE REVIEW

**Comment by Eskibear** [comment]
no idea why above error occur. command not registered, is it indicating the extension is not activated?

**Comment by CsCherrYY** [comment]
Is there any condition that the command registration will be based on?

**Comment by Eskibear** [comment]
> Is there any condition that the command registration will be based on?

No. the registration is directly in `activate` function. And it worked well locally on my machine. That's strange, no idea what was happening.

**Comment by Eskibear** [comment]
I think I found the root cause.

https://github.com/microsoft/vscode-spring-boot-dashboard/commit/81d7c3f108cc9ee16044326de8d358416d16cbb5#diff-89ec1c890fa4805317e8f88cc60346f98ce4a04619e1aab5b315280d9a80cc0dR26-R27

Here introduced some proposed APIs not yet ready on vscode-spring-boot stable version, so it blocks consequent command registration in `activate` method.

**Review by CsCherrYY — APPROVED** [review]

**Pull request merged**
