### PR TITLE
vscode graphical memory view

### PR DESCRIPTION
**Pull request by vudayani-vmw**

### CODE REVIEW

**Comment by vudayani-vmw** [comment]
@microsoft-github-policy-service agree [company="{vmware}"]

**Comment by martinlippert** [comment]
@Eskibear This is the first attempt at showing a live memory graph (as part of the Spring Boot Dashboard, in the same way than the live beans and live request mappings are shown) that we talked about in the past. As this requires some additional API on the Spring Tools extension, you might need to wait a little bit for us to ship a nightly build of the Spring Tools extension with that API in order to try this out. I will keep you updated on this.

This is also meant as a starting point, I am sure you have tons of suggestions/thoughts on how to change/improve this and we are looking forward to your feedback.

**Comment by Eskibear** [comment]
Thanks for the contribution. It looks promising. I'll take a look when vscode-spring-boot nightly build is ready.

**Comment by martinlippert** [comment]
We have a CI build now up here that should contain the necessary changes in the Spring Tools extension, you can find it at the end of this page: https://dist.springsource.com/snapshot/STS4/nightly-distributions.html

**Comment by Eskibear** [comment]
I just played for a while, and it was great. Memory view showed when live process was connected. And it worked well even for multiple-root workspaces.

#### Found a bug:
- collapse and re-expand memory view, then it's broken. As below

https://user-images.githubusercontent.com/2351748/198921291-1f9efead-4783-4448-a4c9-b60a25be7035.mp4

#### Some other thoughts:

Switching between categories loses previous data. E.g. I was watching heap mem for a while and switched to GC pauses. When I switched back to view heap mem, the plot was re-render from scratch, and I could not see previous data. And it only visualized data within the last minute. I could not explicitly start/pause it, which would be less convenient if I want to do further analysis. But it makes sense if it's designed just for monitoring. After all users can still use other JDK tools to do analysis.

**Comment by vudayani-vmw** [comment]
@Eskibear Thanks for the feedback. The bug related to collapsing and re-rendering the memory view is fixed. 
Do you have any further feedback on the changes?

**Comment by Eskibear** [comment]
@vudayani-vmw Thank you!

> I would suggest that we create a separate issue for this improvement and work on that once we have this first step merged and available.

@martinlippert It makes total sense. I'll verify it tomorrow and get it merged ASAP, then we can have the feature in pre-release version.

**Pull request merged**
