### PR TITLE
UX fixes for #241

### PR DESCRIPTION
**Pull request by vudayani-vmw**
- Apply vscode memory view settings (max data points and interval) to live processes
- Plot the graph without the initial delay when the memory view is loaded
- Fix chart js error when switching between graph types
  ```
  chart.min.js:13 Invalid scale configuration for scale: x
  ```

### CODE REVIEW

**Comment by vudayani-vmw** [comment]
@Eskibear This PR addresses the UX issues mentioned in https://github.com/microsoft/vscode-spring-boot-dashboard/pull/239#issuecomment-1313205616

Do we still need to update the description for the setting configurations?

**Comment by Eskibear** [comment]
I'll give it a try ASAP.

> Do we still need to update the description for the setting configurations?

Not necessarily, if the setting is applied immediately on change. I think users can see the changes on graph and won't be confused.

**Comment by Eskibear** [comment]
Found a graph issue with how you plot it.

The x-axis is not correctly scaled after I change settings for polling inteval. Below is the case I change it: 5000 --(at 9:45:19)-> 1000 --(at 9:45:24)-> 5000. 

image

**Comment by Eskibear** [comment]
Compatibility issue:
Working with previous version of vscode-spring-boot where "metrics" apis are not available, it prints errors in console and the memory view shows two buttons without graph, making is wired. Suggest to check whether corresponding API is there before showing memory view.

**Comment by Eskibear** [comment]
UX improvement.


image

With default layout, graph is not presented well in memory view, and you have to scroll to see it. To have the best practice you have to increase width of sidebar.
I think we can make more use of the visual space of memory view, with below suggestions:
- place the two drop-downs into the same row, and maybe put at the bottom, below the graph.
- adjust size of legend/labels of the graph, to **show more about the plot part**.
- better to make the page **responsive**, i.e., especially when width is small, currently it's not much helpful, as below.

image

**Comment by Eskibear** [comment]
Thank you @vudayani-vmw . The PR fixes the issue mentioned in description, so I'm merging it and creating issues for follow-up actions.

**Pull request merged**
