### PR TITLE
update decoration when change/save .java files

### PR DESCRIPTION
**Pull request by Eskibear**
Signed-off-by: Yan Zhang <yanzh@microsoft.com>

### CODE REVIEW

**Comment by Eskibear** [comment]
Before:


https://user-images.githubusercontent.com/2351748/199197036-c7a11909-b0ac-49f1-be3d-caf073bfe86c.mp4


With this PR:

https://user-images.githubusercontent.com/2351748/199188656-97d2aa4e-ca76-4814-91f2-63267f903dd9.mp4

**Comment by Eskibear** [comment]
@jdneo Do you think we should also include this PR in the first release of this feature?

I vote yes because current behavior somehow blocks users from editing code.

**Comment by Eskibear** [comment]
image

Probably I can update this PR, making gutters of a) placeholders and b) beans/mappings of different types. Then it might not change gutter of beans/mappings during editing, only appending placeholders.

**Comment by jdneo** [comment]
> @jdneo Do you think we should also include this PR in the first release of this feature?

Definitely yes

> Probably I can update this PR, making gutters of a) placeholders and b) beans/mappings of different types. 
Not sure how complex it would be - considering if the document change is a combination of adding/removing/multi-line, etc...

**Review by jdneo — DISMISSED** [review]

**Pull request merged**
