### PR TITLE
render spring icons as gutters

### PR DESCRIPTION
**Pull request by Eskibear**
This PR uses `ThemableDecorationRenderOptions.gutterIconPath` to render spring gutter icons, while previously it's mimic by adding icons/placeholders using `:before` styling for each line.

### CODE REVIEW

**Comment by Eskibear** [comment]
Pros:
- No wired bugs when turning on/off word wrapping. should fix #257 
- No need to re-calculate decorations on document change, vscode handles that. Better performance.
- Potential context menus on right click. Proposed in https://github.com/microsoft/vscode/issues/175945

Cons:
- Currenly no hover messages directly on the icon, you have to hover on the line in editor.
- You cannot set breakpoint on the line. See https://github.com/microsoft/vscode/issues/5923 
  - not a big impact here as beans/mappings are all annotations

**Comment by Eskibear** [comment]
Demo: 

https://user-images.githubusercontent.com/2351748/224916230-9289c522-ac3f-4ae3-8101-f96013be06e2.mp4

**Comment by nickzhums** [comment]
Nice, qq, at 0:04, when you clicked the icon, what happened?

**Comment by Eskibear** [comment]
> Nice, qq, at 0:04, when you clicked the icon, what happened?

Nothing happens now. But with vscode's proposed API, we can put some commands there. The UI is Like something as below:
image

**Comment by nickzhums** [comment]
> > Nice, qq, at 0:04, when you clicked the icon, what happened?
> 
> Nothing happens now. But with vscode's proposed API, we can put some commands there. The UI is Like something as below: image

Nice, that would be useful in the future. Looks good to me

**Review by nickzhums — APPROVED** [review]

**Comment by Eskibear** [comment]
Follow-up:

- Potential context menus on right click. Proposed in https://github.com/microsoft/vscode/issues/175945 When the API is ready, we can register some useful commands there.

**Pull request merged**
