### PR TITLE
support to run apps with profile

### PR DESCRIPTION
**Pull request by Eskibear**

### CODE REVIEW

**Comment by Eskibear** [comment]
DEMO: 

https://user-images.githubusercontent.com/2351748/230528962-0e9f9b59-dbe6-4890-8c1b-e3847a931974.mp4

**Comment by getaceres** [comment]
How does it detect the profiles? I have several yml files in /src/main/resources with the format application-<profile>.yml but I can't select any profile from the launcher. Does it only look for .properties?

**Comment by Eskibear** [comment]
> Does it only look for .properties?

Yes, exactly, for the moment. I followed STS4 to implement this feature. See https://github.com/microsoft/vscode-spring-boot-dashboard/pull/309/files#diff-c4b049f473e6cb9eb7cc8631c5b93726d41dd11a7b61263a4d291e18cada4b85R91

It's a good catch! Tracked in #315 . The impl should be trivial and I'll invite @testforstephen to fix it.

**Comment by 07Yusuf11** [comment]
it doesn't recognize *.yml and bootstrap-<profile>.yml

**Comment by Eskibear** [comment]
> *.yml and bootstrap-.yml

Are they expected to be recognized as profiles? Can you point the document? 
cc @testforstephen

**Pull request merged**
